name: CI

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  # Event `pull_request`: Compare the last commit of the main branch or last remote commit of the PR branch -> to the current commit of a PR branch.
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  changed_only_netid:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test netid file
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get the files that were changed.
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: |
            netids:
              - '[a-z]*.md'

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Assert only one file was changed.
        # NOTE: Ensure all outputs are prefixed by the same key used above e.g. `test_(...)` | `doc_(...)` | `src_(...)` when trying to access the `any_changed` output.
        if: steps.changed-files.outputs.all_changed_files_count != 1
        run: |
          echo "::error::More than one file was changed." && exit 1
      
      - name: Assert file changed was a netid file.
        if: steps.changed-files.outputs.netids_changed_files_count != 1
        run: |
          echo "::error::Changed a file other than your netid markdown." && exit 1
